language: node_js
node_js:
  - '12.7.0'
dist: trusty

before_script:
  - npm run server &

script:
  - npm run build
  - sleep 30
  - pushd ./build
  - python -m SimpleHTTPServer 3000 &
  - popd
  - sleep 30
  - npm run test

after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
  - bash scripts/gitbook.sh
